config/routes.rb
Rails.application.routes.draw do
  resources :riddles do
    resources :comments, except: [:index, :show] do
      resources :comment_votes, only: [:create]
    end
    resources :riddle_votes, only: [:create]
  end

  resources :users, except: [:index, :new, :create]

  root 'riddles#index'

  get 'unanswered' => 'riddles#unanswered'
  get 'answered' => 'riddles#answered'

  get 'signup/new' => 'sessions#new'
  post 'signup' => 'sessions#create'

  get 'login' => 'sessions#login_form', as: "login_form"
  post 'login' => 'sessions#login', as: "login"

  get 'logout' => 'sessions#logout', as: :logout

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :riddle
  has_many :comment_votes
  validates :body, presence: true

  def vote_count
     comment_votes.count
  end
end

app/models/comment_vote.rb
class CommentVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/models/riddle.rb
class Riddle < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :riddle_votes, :dependent => :destroy

  def vote_count
    riddle_votes.count
  end

end

app/models/riddle_vote.rb
class RiddleVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :riddle
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true
  validates :email, presence: true
  validates_uniqueness_of :email

  has_many :riddles
  has_many :comments
  has_many :riddle_votes
  has_many :comment_votes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :ensure_current_user, except: 'riddles#index'
  helper_method :current_user

  def ensure_current_user
    redirect_to login_path unless current_user
  end

  def current_user
    return User.find_by(id: session[:user_id])
  end
end

app/controllers/comment_votes_controller.rb
class CommentVotesController < ApplicationController
  def create
    @comment_vote = CommentVote.where(comment_id: params[:comment_id], user_id: current_user.id).first_or_create

    number = Comment.find_by(id: params[:comment_id]).comment_votes.count

    respond_to do |format|
      format.html{redirect_to @comment_vote.comment.riddle}
      format.json{render json: number}
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
  	@riddle = Riddle.find_by_id(params[:riddle_id])
  	@comment = Comment.new
  end

  def create
  	new_comment = Comment.new(comment_params)
  	if new_comment.save
  	  riddle = Riddle.find_by_id(params[:riddle_id])
  	  user = User.find_by_id(session[:user_id])
  	  riddle.comments << new_comment
  	  user.comments << new_comment
  		redirect_to riddle_path(riddle)
  	else
      @riddle = Riddle.find_by_id(params[:riddle_id])
      @comment = Comment.new
  		render :new
  	end
  end

  def edit
  	@comment = Comment.find_by_id(params[:id])
    @riddle = Riddle.find_by_id(params[:riddle_id])
  end

  def update
  	comment = Comment.find_by_id(params[:id])
    comment.update_attributes(comment_params)
    redirect_to riddle_path(Riddle.find_by_id(params[:riddle_id]))
  end

  def destroy
  	comment = Comment.find_by_id(params[:id])
  	comment.destroy
  	redirect_to riddle_path(Riddle.find_by_id(params[:riddle_id]))
  end

  private

  def comment_params
  	params.require(:comment).permit(:body)
  end



end

app/controllers/riddle_votes_controller.rb
class RiddleVotesController < ApplicationController

  def create
    @riddle_vote = RiddleVote.where(riddle_id: params[:riddle_id], user_id: current_user.id).first_or_create
    number = Riddle.find_by(id: params[:riddle_id]).riddle_votes.count
    respond_to do |format|
      format.html{redirect_to @riddle_vote.riddle}
      format.json{render json: number}
    end
  end

  private

  def riddle_votes_params
    params.require(:riddle).permit(:riddle_id).merge(user_id: current_user.id)
  end

end

app/controllers/riddles_controller.rb
class RiddlesController < ApplicationController

skip_before_filter :ensure_current_user

  def index
    @ans_riddles = Riddle.where('answer is not null').sort_by {|r| r.riddle_votes.count}.reverse[0..5]

    @uns_riddles = Riddle.where('answer is null').sort_by {|r| r.riddle_votes.count}.reverse[0..5]
  end

  def new
    @riddle = Riddle.new
  end

  def show
    find_riddle(params[:id])
     @riddle_vote = RiddleVote.new
     vote_count(params[:id])
  end

  def create
    @riddle = Riddle.new riddle_params
    if @riddle.save
      redirect_to @riddle
    else
      render :new
    end
  end

  def edit
    find_riddle(params[:id])
  end

  def update
    find_riddle(params[:id])
    if @riddle.update_attributes(riddle_params)
      redirect_to @riddle
    else
      render :new
    end
  end

  def destroy
    riddle = Riddle.find_by(id: params[:id])

    riddle.destroy
    redirect_to riddles_path
  end

  def unanswered
    @riddles = Riddle.where('answer is null').sort_by {|r| r.riddle_votes.count}.reverse
    render 'riddles/showall'
  end

  def answered
    @riddles = Riddle.where('answer is not null').sort_by {|r| r.riddle_votes.count}.reverse
    render 'riddles/showall'
  end

  private

  def riddle_params
    riddle_p = params.require(:riddle).permit(:title, :body, :answer).merge(user_id: current_user.id)
    if /\w/.match(riddle_p[:answer]) == nil
      riddle_p[:answer] = nil
    end
    riddle_p
  end

  def find_riddle id
    @riddle = Riddle.find(id)
  end
  def vote_count id
    @count = RiddleVote.where(riddle_id: id).count
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :ensure_current_user

  def new
    @user = User.new
  end

  def create
    new_user = User.new(allowed_params)

    if new_user.save
      session[:user_id] = new_user.id
      redirect_to riddles_path
    else
      redirect_to signup_new_path
    end
  end

  def login
    @user = User.find_by_email(params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to riddles_path
    else
      redirect_to login_form_path
    end
  end

  def logout
    session.clear
    redirect_to root_path
  end

  private

  def allowed_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find_by_id(params[:id])
	end

	def edit
		@user = User.find_by_id(params[:id])
	end

	def update
		user = User.find_by_id(params[:id])
		update_params = rip_empty(user_params)
		user.update_attributes(update_params)
		redirect_to user_path(user)
	end

	def destroy
		user = User.find_by_id(params[:id]).destroy
		session.clear
		redirect_to root_path
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end

	def rip_empty(hash)
		hash.delete_if do |key, value|
  		value == ""
  	end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_answered array
    array.first.answer
  end

end

app/views/comments/_index.html.erb
	<%= link_to 'New Comment', '#', class: 'show_new_form'%>
	<div class="new_comment_form initiallyHidden">
		<%= render partial: 'comments/new', locals: {riddle: @riddle, comment: Comment.new} %>
	</div>
	<div class="answers">Answers</div>
		<% riddle.comments.each do |comment| %>
			<%= render partial: 'comments/show', locals: {riddle: riddle, comment: comment } %>
		<% end %>

app/views/comments/_new.html.erb
<%= form_for [riddle, comment] do |f| %>
  <%= f.text_area :body, class: "form-field comment-form-field", placeholder: "comment" %>
  <%= f.submit class: "btn" %>
<% end %>

app/views/comments/_show.html.erb
<div class="comment">
	<div class="comment-body"><%= comment.body %></div>

	<div class="comment_tags">
		<div class="comment-btn" id="<%= comment.id %>">
			<%= comment.vote_count %>
		</div>

		<div class="comment-btn">
			<%= form_for([riddle, comment, CommentVote.new]) do |f| %>
	  		<%= f.submit "| upvote", class: "comment-btn" %>
			<% end %>
		</div>

		<div class="comment_mods comment-btn">
			<% if session[:user_id] == comment.user_id %>

			<div class="comment-btn">
				<%= link_to "| Edit |", edit_riddle_comment_path(@riddle, comment), class: 'comment-btn' %>
			</div>

				<%= link_to "Delete", riddle_comment_path(@riddle, comment), data: { confirm: 'Are you sure you want to delete your comment?' }, method: :delete, class: 'comment-btn' %>
			<% end %>
		</div>

		<div class="comment-stamp"><%= comment.user.username %>
			<% if comment.created_at.to_i == comment.updated_at.to_i %>
				@
			<% else %>
				edited @
			<% end %>
			<%= comment.updated_at.ctime %></div>
	</div>
</div>

app/views/comments/edit.html.erb
<div class="container">

  <%= form_for [@riddle, @comment] do |f| %>
    <%= f.text_area :body, class: "form-field .tall-form-field comment-form-field", placeholder: "comment"  %>

    <%= f.submit class: "btn inline-btn" %>
  <% end %>

  <%= button_to('Destroy', riddle_comment_path(@riddle, @comment), method: :delete, class: "btn inline-btn" ) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RiddleMeThis</title>
    <%= stylesheet_link_tag 'application','http://fonts.googleapis.com/css?family=Megrim' %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Quicksand:300,400,700' %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Sacramento:300,400,700' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrapper">
      <header>
        <div class="nav-link nav-side left-nav-link"><%= link_to "RiddleMeThis", root_path %></div>
        <div class="nav-side right-nav-link">
          <% if current_user %>
          <div class="nav-link nav-link-1"><%= link_to "Submit Riddle", new_riddle_path %></div>
          <div class="nav-link nav-link-2"><%= link_to "Logout", logout_path %></div>
          <% else %>
          <div class="nav-link nav-link-1"><%= link_to "Signup", signup_new_path %></div>
          <div class="nav-link nav-link-2"><%= link_to "Login", login_form_path %></div>
          <% end %>
        </div>
      </header>

      <div class="container"></div>
      <div id="body">
      <%= yield %>
      </div>
      <div class="footer">
        <span class="footer-text">Made with</span>
        <%= image_tag 'heart.png', class: 'heart-img' %>
        <span class="footer-text">by</span>
        <a class="footer-text" href="https://github.com/sagararathi" target="_blank">sagararathi &</a>
        <a class="footer-text" href="https://github.com/kjb085" target="_blank">kjb085 &</a>
        <a class="footer-text" href="https://github.com/ivanyukio" target="_blank">ivanyukio &</a>
        <a class="footer-text" href="https://github.com/jjparseghian" target="_blank">jjparseghian &</a>
        <a class="footer-text" href="https://github.com/rosapergams" target="_blank">rosapergams</a>
      </div>
    </div>
  </body>
</html>

app/views/riddles/_form.html.erb
 <%= form_for @riddle do |f| %>
  <%= f.text_field :title, class: "form-field", placeholder: "title"  %>

  <%= f.text_area :body, class: "form-field tall-form-field", placeholder: "body"  %>

  <%= f.text_field :answer, class: "form-field", placeholder: "answer"  %>
  <%= f.hidden_field(:user_id, value: session[:user_id] ) %>
   <%= f.submit class: "btn" %>
<% end %>

app/views/riddles/edit.html.erb
<div>
<%= render "form" %>
</div>

app/views/riddles/index.html.erb
<div class="landing-page-img">
  <%= image_tag 'lightbulb.png', class: 'logo-img' %>
  <div class="tagline">A riddle &amp; answer site for the curious.</div>
</div>

<div class="container">
  <div class="title"><%=  link_to "Unanswered Riddles", unanswered_path %></div>
  <% @uns_riddles.each do |r| %>
  <div class="riddle-link">
    <%= link_to "#{r.title}", riddle_path(r) %>
      <span class="upvotes_comments"><%= r.vote_count %> upvotes &
      <%= r.comments.count %> comments</span>
  </div>
  <% end %>

  <br>

  <div class="title"> <%=  link_to "Answered Riddles", answered_path%></div>
  <% @ans_riddles.each do |r| %>
  <div class="riddle-link">
    <%= link_to "#{r.title}", riddle_path(r) %>
      <span class="upvotes_comments"><%= r.vote_count %> upvotes &
      <%= r.comments.count %> comments</span>
  </div>
  <% end %>
</div>

app/views/riddles/new.html.erb
<div>
<%= render "form" %>
</div>

app/views/riddles/show.html.erb
<div class="container">
  <div class="riddle_title">
    <%= @riddle.title %>
  </div>

  <div id='riddle_body'>
    <%= @riddle.body %>
  </div>

  <% if @riddle.answer %>
    <%= button_to "Show Answer", @riddle.answer, form_class: 'show_ans', class: "ans_btn btn"  %>
  <% end %>

  <div id='riddle_ans' class='initiallyHidden'>
    <%= @riddle.answer %>
  </div>

  <div class="comment-btn">
    <%= @count %>
  </div>

  <div class="comment-btn">
    <%= form_for([@riddle, @riddle_vote]) do |f| %>
      <%= f.submit "| upvote", class: "comment-btn"%>
    <% end %>
  </div>

  <% if current_user %>
    <% if @riddle.user_id == current_user.id %>
      <div class="comment-btn">
        <%= button_to '| Edit |', edit_riddle_path(@riddle), method: :get, class: "comment-btn"%>
      </div>
      <div class="comment-btn">
        <%= form_for(@riddle, :method => :delete) do |f| %>
          <%= f.submit "Delete", class: "comment-btn"%>
      </div>
      <% end %>
    <% end %>
  <% end %>

  <%= render partial: 'comments/index', locals: {riddle: @riddle} %>
</div>

app/views/riddles/showall.html.erb
<div class="container">
  <% if is_answered(@riddles) %>
    <div class="title">Answered Riddles</div>
  <% else %>
    <div class="title">Unanswered Riddles</div>
  <% end %>

  <% @riddles.each do |r| %>
  <div class="riddle-link">
    <%= link_to "#{r.title}", riddle_path(r) %>
      <span class="upvotes_comments"><%= r.vote_count %> upvotes &
      <%= r.comments.count %> comments</span>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
<ul>
	<%= form_for @user do |f| %>
		<li>
			<%= f.label :username %>:
  		<%= f.text_field :username %>
  	</li>

  	<li>
		  <%= f.label :email %>:
		  <%= f.text_field :email %>
		</li>

		<li>
	  	<%= f.label :password %>:
	  	<%= f.password_field :password %>
	  </li>

	  <li>
		  <%= f.label :password_confirmation %>:
		  <%= f.password_field :password_confirmation %>
		</li>
		
	  <%= f.submit %>
	<% end %>
</ul>
</div>

app/views/users/show.html.erb
<div class="container">
	<h1><%= @user.username %></h1>
	<% if current_user %>
		<% if @user.id == current_user.id %>
			<%= link_to "Edit", edit_user_path(@user) %>
			<%= link_to "Delete", user_path(@user), data: { confirm: 'Are you sure you want to delete your account?' }, method: :delete %>
		<% end %>
	<% end %>
	<h3><%= @user.username %>'s Riddles:</h3>
	<ul>
		<% @user.riddles.each do |riddle| %>
			<li>
				<p><%= link_to "#{riddle.title}", riddle_path(riddle) %></p>
				<p>Upvotes: <%= riddle.riddle_votes.count %></p>
			</li>
		<% end %>
	</ul>
</div>